### PR TITLE
adding donations, financials, chicago html/url/views

### PR DESCRIPTION
**Pull request by RachellCalhoun**
added three more pages following the why peru page format, view and html

### CODE REVIEW

**Comment by RachellCalhoun** [comment]
@jinpark  this is a follow up to my last PR, can you look at it. no models were created so it should be fine.

**Comment by RachellCalhoun** [comment]
@jinpark can you check this over?

**Comment by jinpark** [comment]
seems fine. this seems very repetitive though.

**Comment by RachellCalhoun** [comment]
Yep, If you wanna have a go at it? lol I'm doing what i know how.

**Comment by jinpark** [comment]
its probably better to get this out and show it to the client and make sure shes ok with it first

**Pull request merged**
