### PR TITLE
setup childrenspage

### PR DESCRIPTION
**Pull request by RachellCalhoun**
all backend and front-end seems pretty much done.

### CODE REVIEW

**Comment by RachellCalhoun** [comment]
#4 
childrensprogram

**Comment by RachellCalhoun** [comment]
Im going to fix mobile responsive stuff. Don't merge yet!

**Comment by RachellCalhoun** [comment]
fixed mobile by doing push/pull 

screenshot from 2016-03-02 20 58 54

**Comment by RachellCalhoun** [comment]
@JiwonHwang can you look at this and 'merge pull request ' if it looks ok?

**Comment by hassanabidpk** [comment]
@RachellCalhoun  put the famous dummy text "Lorem ipsum ... "

**Comment by hassanabidpk** [comment]
Is this related to pull request #16 ?

**Comment by RachellCalhoun** [comment]
i'm going to close this? since it's on #16

**Pull request merged**
