### PR TITLE
make spanish menu work

### PR DESCRIPTION
**Pull request by jinpark**
@RachellCalhoun how bout htis?

### CODE REVIEW

**Comment by RachellCalhoun** [comment]
I tried it out and when I go to the spanish pages the english menu is still there. I entered some spanish menus and english menus. It's the same problem I was having ...only one or the other through the whole site. 


english_menu

**Comment by RachellCalhoun** [comment]
I tried to check it out and from what I can see, the English menu is always there even on the spanish pages. Does this work for you? 
english_menu

**Comment by jinpark** [comment]
@RachellCalhoun check again

and make sure you understand what I did to make it work and why it didnt work on my first attempt

**Comment by RachellCalhoun** [comment]
Thanks! I had a look at it and it worked yay!! Seems like it was so simple.

**Pull request merged**
